import { type Metadata } from 'next'
import '@/app/globals.css'
import Footer from '@/components/general/Footer'
import { SecondaryNavbar } from '@/components/general/SecondaryNavbar'
export const metadata: Metadata = {
  title: 'HushBoard',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      
          <SecondaryNavbar/>
          <div className=''>
          {children}
          </div>         
    </>
  )
}