import { type Metadata } from 'next'
import '@/app/globals.css'
import Footer from '@/components/general/Footer'
import { Navbar } from '@/components/general/Navbar'
export const metadata: Metadata = {
  title: 'HushBoard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      
          <Navbar/>
          <div className=''>
          {children}
          </div>
         
          <Footer/>
    </>
  )
}