import { type Metadata } from 'next'
import './globals.css'
import PageLoader from '@/components/PageLoader'
import { ThemeProvider } from '@/components/theme-provider'
import { Toaster } from 'sonner'

export const metadata: Metadata = {
  title: 'HushBoard',
  description: 'Generated by create next app',
  
  
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    
      <html lang="en" >
        <body className='overflow-x-hidden'>
         <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            disableTransitionOnChange
            
         >
          <Toaster richColors/>
          <PageLoader/>
          {children}
        </ThemeProvider> 
        </body>
      </html>
    
  )
}